<?php

/**
 * BaseQuestionCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property varchar $name
 * @property Doctrine_Collection $Question
 * 
 * @method varchar             getName()     Returns the current record's "name" value
 * @method Doctrine_Collection getQuestion() Returns the current record's "Question" collection
 * @method QuestionCategory    setName()     Sets the current record's "name" value
 * @method QuestionCategory    setQuestion() Sets the current record's "Question" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseQuestionCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('question_category');
        $this->hasColumn('name', 'varchar', 128, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 128,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Question', array(
             'local' => 'id',
             'foreign' => 'category_id'));
    }
}