<?php

/**
 * BaseAnswer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $evaluation_id
 * @property integer $question_id
 * @property integer $value
 * @property Question $Question
 * @property Evaluation $Evaluation
 * 
 * @method integer    getEvaluationId()  Returns the current record's "evaluation_id" value
 * @method integer    getQuestionId()    Returns the current record's "question_id" value
 * @method integer    getValue()         Returns the current record's "value" value
 * @method Question   getQuestion()      Returns the current record's "Question" value
 * @method Evaluation getEvaluation()    Returns the current record's "Evaluation" value
 * @method Answer     setEvaluationId()  Sets the current record's "evaluation_id" value
 * @method Answer     setQuestionId()    Sets the current record's "question_id" value
 * @method Answer     setValue()         Sets the current record's "value" value
 * @method Answer     setQuestion()      Sets the current record's "Question" value
 * @method Answer     setEvaluation()    Sets the current record's "Evaluation" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAnswer extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('answer');
        $this->hasColumn('evaluation_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('question_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('value', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Question', array(
             'local' => 'question_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Evaluation', array(
             'local' => 'evaluation_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}