<?php

/**
 * BaseQuestion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property text $text
 * @property integer $type_id
 * @property integer $category_id
 * @property QuestionType $QuestionType
 * @property QuestionCategory $QuestionCategory
 * @property Doctrine_Collection $Answer
 * 
 * @method text                getText()             Returns the current record's "text" value
 * @method integer             getTypeId()           Returns the current record's "type_id" value
 * @method integer             getCategoryId()       Returns the current record's "category_id" value
 * @method QuestionType        getQuestionType()     Returns the current record's "QuestionType" value
 * @method QuestionCategory    getQuestionCategory() Returns the current record's "QuestionCategory" value
 * @method Doctrine_Collection getAnswer()           Returns the current record's "Answer" collection
 * @method Question            setText()             Sets the current record's "text" value
 * @method Question            setTypeId()           Sets the current record's "type_id" value
 * @method Question            setCategoryId()       Sets the current record's "category_id" value
 * @method Question            setQuestionType()     Sets the current record's "QuestionType" value
 * @method Question            setQuestionCategory() Sets the current record's "QuestionCategory" value
 * @method Question            setAnswer()           Sets the current record's "Answer" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseQuestion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('question');
        $this->hasColumn('text', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('type_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('QuestionType', array(
             'local' => 'type_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('QuestionCategory', array(
             'local' => 'category_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Answer', array(
             'local' => 'id',
             'foreign' => 'question_id'));
    }
}