<?php

/**
 * BaseQuestionType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property varchar $class_name
 * @property Doctrine_Collection $Question
 * 
 * @method varchar             getClassName()  Returns the current record's "class_name" value
 * @method Doctrine_Collection getQuestion()   Returns the current record's "Question" collection
 * @method QuestionType        setClassName()  Sets the current record's "class_name" value
 * @method QuestionType        setQuestion()   Sets the current record's "Question" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseQuestionType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('question_type');
        $this->hasColumn('class_name', 'varchar', 128, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 128,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Question', array(
             'local' => 'id',
             'foreign' => 'question_type_id'));
    }
}