<?php

/**
 * EvaluationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EvaluationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EvaluationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Evaluation');
    }

    public static function getRanking($site_type = null)
    {
      $q = Doctrine_Query::create()
        ->from('Evaluation e');

      if($site_type)
      {
        $q->leftJoin('e.Site s')
          ->leftJoin('s.SiteType st')
          ->where('st.name = ?', $site_type);
      }

      $q->orderBy('e.result DESC');

      return $q->execute();
    }
}
