<?php

/**
 * EvaluationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EvaluationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EvaluationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Evaluation');
    }
}