<?php

/**
 * QuestionTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class QuestionTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object QuestionTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('QuestionType');
    }
}