<?php

/**
 * QuestionCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class QuestionCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object QuestionCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('QuestionCategory');
    }
}