<?php

/**
 * SiteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SiteTable extends Doctrine_Table
{
    const DEALER = 'Marchand';
    const SHOWCASE = 'Vitrine';

    /**
     * Returns an instance of this class.
     *
     * @return object SiteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Site');
    }

    public static function getDealers()
    {
      return self::getSiteType(self::DEALER);
    }

    public static function getShowcases()
    {
      return self::getSiteType(self::SHOWCASE);
    }

    public static function getSiteType($type)
    {
      $q = Doctrine_Query::create()
        ->from('Site s')
        ->leftJoin('s.SiteType st')
        ->where('st.name = ?', $type);

      return $q->execute();
    }
}
