<?php

/**
 * SiteTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SiteTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SiteTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SiteType');
    }
}