# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

init_evaluation:
  url: /:site_id/init_evaluation
  param: { module: website, action: initEvaluation }
  requirements:
    site_id: \d+
    
edit_evaluation:
  url: /:evaluation_id/edit_evaluation
  param: { module: website, action: initEvaluation }
  requirements:
    evaluation_id: \d+

question:
  url: /:evaluation_id/question/:category_id
  param: { module: website, action: question }
  requirements:
    evaluation_id: \d+
    category_id: \d+

# default rules
homepage:
  url:   /
  param: { module: website, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
