all:
  doctrine:
   class:        sfDoctrineDatabase
   param:
     classname:  DebugPDO
     dsn:        mysql:dbname=WebsiteEval;host=localhost
     username:   WebsiteEval
     password:   websiteeval
     encoding:   utf8
     persistent: true
     pooling:    true
