Site:
  actAs:          { Timestampable: ~ }
  columns:
    url:          { type: varchar(128), notnull: true }
    owner:        { type: varchar(128), notnull: true }
    creator:      { type: varchar(128), notnull: true }
    site_type_id: { type: integer, notnull: false }
  relations:
    SiteType:     { onDelete: SET NULL, local: site_type_id, foreign: id }

SiteType:
  columns:
    name: { type: varchar(128), notnull: true }

Evaluation:
  actAs:     { Timestampable: ~ }
  columns:
    site_id: { type: integer, notnull: true }
    is_over: { type: boolean, default: false }
  relations:
    Site:    { onDelete: CASCADE, local: site_id, foreign: id }

Question:
  columns:
    text:             { type: text, notnull: true }
    site_type_id:     { type: integer, notnull: false }
    question_type_id: { type: integer, notnull: false }
    category_id:      { type: integer, notnull: false }
  relations:
    SiteType:         { onDelete: SET NULL, local: site_type_id, foreign: id }
    QuestionType:     { onDelete: SET NULL, local: question_type_id, foreign: id }
    QuestionCategory: { onDelete: CASCADE, local: category_id, foreign: id }

QuestionType:
  columns:
    class_name: { type: varchar(128), notnull: true }

QuestionCategory:
  columns:
    name: { type: varchar(128), notnull: true }

Answer:
  columns:
    evaluation_id:  { type: integer, primary: true }
    question_id:    { type: integer, primary: true }
    value:          { type: integer, notnull: true }
  relations:
    Question:   { onDelete: CASCADE, local: question_id, foreign: id }
    Evaluation: { onDelete: CASCADE, local: evaluation_id, foreign: id }
